
# MODEL hparams
[[hparams]]
name = "complexity"
suggest = "categorical"
choices = ["small", "medium", "large", "xl"]

# this refers to the previous table entry in the hparams arraytable, ie complexity
[hparams.map]
small = { num_heads = 4, n_enc_layers = 5 }
medium = { num_heads = 8, n_enc_layers = 10 }
large = { num_heads = 16, n_enc_layers = 15 }
xl = { num_heads = 32, n_enc_layers = 20 }

[[hparams]]
name = "embed_scale"
suggest = "categorical"
choices = [1, 2, 4, 8]


[[hparams]]
name = "dropout"
suggest = "float"
low = 0.0
high = 0.5
log = false

[[hparams]]
name = "layer_dropout"
suggest = "float"
low = 0.0
high = 0.2
log = false

# OPTIMIZER hparams
[[hparams]]
name = "lr"
suggest = "float"
low = 5e-4
high = 5e-2
log = true
parent = "optimizer"

[[hparams]]
name = "weight_decay"
suggest = "float"
low = 1e-3
high = 1e-1
log = true
parent = "optimizer"

# DATA hparams
[[hparams]]
name = "batch_size"
suggest = "categorical"
choices = [8, 16, 32]
parent = "data"

[[hparams]]
name = "chunk_size"
suggest = "int"
low = 15
high = 50
step = 5
parent = "data"

# LOSS hparams
[[hparams]]
name = "margin"
suggest = "float"
low = 0.1
high = 10.0
log = true
parent = "loss"

# AUGMENTATION hparams
[[hparams]]
name = "sample_scale"
suggest = "float"
low = 1.0
high = 15.0
log = false
parent = "augmentation"

[[hparams]]
name = "sample_rate"
suggest = "float"
low = 0.25
high = 0.75
log = false
parent = "augmentation"

[[forbidden]]
complexity = "xl"
batch_size = 32

[[forbidden]]
complexity = "xl"
batch_size = 16

[[forbidden]]
complexity = "large"
batch_size = 32

[[forbidden]]
complexity = "xl"
embed_scale = 1

[[forbidden]]
complexity = "large"
embed_scale = 1
