universe = vanilla
executable = predict_run.sh
output = $(Cluster)_$(Process).out
get_env = STAGING, USER
arguments = $(data) $(outdir) $(devices) $(checkpoint)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

Requirements = (Target.HasCHTCStaging == true)

require_gpus = (DriverVersion >= 11.6) && (GlobalMemoryMB >= 32768)
request_gpus = $(devices)

+WantGPULab = true
+GPUJobLength = "short"

request_cpus = 1
request_memory = $(memory)
request_disk = $(disk)

log = $(Cluster)_$(Process).log
error = $(Cluster)_$(Process).err

queue data,outdir,checkpoint,devices,disk,memory from inputs.csv
